export const actionTypes = {
    FETCH_RSS_INIT: "FETCH_RSS_INIT",
    FETCH_RSS_PROGRESS: "FETCH_RSS_PROGRESS",
    FETCH_RSS_RECEIVED: "FETCH_RSS_RECEIVED",
    FETCH_RSS_ERROR: "FETCH_RSS_ERROR",
    RESET_RSS_STATE: "RESET_RSS_STATE",
    CHANGE_SEARCH_TEXT: "CHANGE_SEARCH_TEXT",
    CLEAR_SEARCH_TEXT: "CLEAR_SEARCH_TEXT"
}